return {
  { "goolord/alpha-nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  -- { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "jose-elias-alvarez/null-ls.nvim", enabled = false },
  { "windwp/nvim-spectre", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "folke/which-key.nvim", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "tpope/vim-repeat", enabled = false },
  { "williamboman/mason-lspconfig.nvim", enabled = false },
  { "folke/trouble.nvim", enabled = false },
  -- { "folke/noice.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
}
